### PR TITLE
Change dockerfile

### PR DESCRIPTION
**Pull request by mandeabhi**
Signed off by: Abhijit Mande <mandeab@vmware.com>

### CODE REVIEW

**Comment by MRHarrison** [comment]
@mandeabhi you need to sign the commit not leave a comment :)

**Comment by mandeabhi** [comment]
My GPG is behaving weird. I added the -S tag and have everything setup in my gitconfig, but not sure why gpg doesn't sign. I guess I'll try uninstalling and reinstalling.

**Comment by MRHarrison** [comment]
@mandeabhi you can amend your commit description with `Signed-off-by: John Doe <john.doe@email.org>`

**Comment by mandeabhi** [comment]
@MRHarrison ah! Wrong way to write signed-off-by.

**Pull request merged**
